export const UPDATE_PARAMETER = 'UPDATE_PARAMETERS';
export const SET_PARAMETERS = 'SET_PARAMETERS';
export const UPDATE_INTERPOLATED_IMG = 'UPDATE_IMAGE_DATA';
export const UPDATE_ORIGINAL_IMG = 'UPDATE_ORIGINAL_IMG';