export const UPDATE_PARAMETER = 'UPDATE_PARAMETERS';
export const SET_PARAMETERS = 'SET_PARAMETERS';
export const UPDATE_INTERPOLATED_IMG = 'UPDATE_IMAGE_DATA';
export const UPDATE_ORIGINAL_IMG = 'UPDATE_ORIGINAL_IMG';
export const SWAP_CAMERA_STATUS = 'SWAP_CAMERA_STATUS';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const UPDATE_FILTER_TEXT = 'UPDATE_FILTER_TEXT';
